### ISSUE TITLE
Kur dingo hą.lt?

### ISSUE THREAD

**Issue by ViliusKraujutis** [makerspacelt/makerspacelt.github.io#10]
Sveiki,

Yra neveikianti nuoroda į hą.lt. Bandžiau atrasti kas pirmasis pridėjo "Hackerių namai H@LT Vilniuje", tai atrodo @grinkus pridėjo šiuo commit'u https://github.com/makerspacelt/makerspacelt.github.io/commit/a5eed41bb807ed5065ffbc03acd495ae62c61966#commitcomment-16782452

Bet panašu, kad po to hą.lt jau dingo iš eterio? Gal kas nors šiaip žinot, kur jie dabar liko?

**Comment by karolis-adapt** [comment]
Gerai, kad į issue numetei :) Kiek pamenu juos būdavo galima rasti freenode #parallax-manufactory [log'as](http://mg.pov.lt/hackerspace-irclog/index.html). Lyg ir atsimenu kažkokį mailing list'ą, bet neberandu kur ir kaip jis buvo.

**Comment by grinkus** [comment]
Issue palieku open, nes reiktų broken link'ą pašalint

**Comment by Pawka** [comment]
@ViliusKraujutis H@LT nebeegzistuoja.
