### ISSUE TITLE
Update space address everywhere

### ISSUE THREAD

**Issue by dariuskt** [makerspacelt/makerspacelt.github.io#11]
- [x] http://makerspace.lt
- [x] http://makerspacelt.tumblr.com
- [x] facebook
- [x] https://wiki.hackerspaces.org/Kaunas_Makerspace
```
Tunelio g. 60, Kaunas
įėjimas iš Motorų g. (vidinis kiemas)
```

**Comment by Asshes** [comment]
Changed @faceboook

**Comment by dariuskt** [comment]
makerspace.lt updated
