### ISSUE TITLE
Main site # Sitemap

### ISSUE THREAD

**Issue by Asshes** [makerspacelt/makerspacelt.github.io#6]
ABOUT US
----
mission
rules
how to join --> project > people > knowledge
our people
emails collect
social plugins
2%
contacts
registration. slack?

WORKPLACE
-----
github
projects list
equipment/tools
events

MEDIA
-----
thumblr/blog
live stream
for the media

**Comment by grinkus** [comment]
Sujungiam su [issue #5][five]. Sujungiu ir uždarau šitą.

[five]: https://github.com/makerspacelt/makerspacelt.github.io/issues/5
