### ISSUE TITLE
pridėti 2% paramos skyrimo instrukciją ir formą popieriniam pildymui

### ISSUE THREAD

**Issue by dariuskt** [makerspacelt/makerspacelt.github.io#8]
Reikia kažkur į web'ą įmontuoti instrukcija su paveiksliukais kaip ten VMI web'e reikia paskirti 2% paramos ir/arba duot parsisiųst formą popieriniam pildymui.

Instrukcijos ir forma pas Vaidą.

**Comment by grinkus** [comment]
[Parama instrukcija.docx](https://github.com/makerspacelt/makerspacelt.github.io/files/155665/Parama.instrukcija.docx)

forma TIF'u jis buvo prisegęs. reiktų paieškot kokio tai labiau elektroniniam pildymui lankstaus formato, o ir github ant TIF pyksta :) PDF'ai tinka.

**Comment by vaidasvt** [comment]
Na, šitų dokų elektroniniu būdu pildyti neišeis. Turi būti parašai, tai jokio tolko nėra jų e-būdu pildyti. Elektroniškai pildoma tik VMI saite. Visur kitur reikia pasiimt lapelius, susirinkt supildytą su parašu ir viskas.

**Comment by grinkus** [comment]
@vaidasvt Nuuuu, tai aš imu pdf'ą, supildau, paprintinu ir nunešu į makerspace. Lyg ir paprastas use-case, kuris būtų galimas support'inti :)

**Comment by grinkus** [comment]
(btw, kątik pridaviau paraišką paduoti tuos 2% space'ui :) juokinga sistema ten...)

**Comment by vaidasvt** [comment]
Jo, juokinga. Realiai, tai taip ir yra. Atsispausdini tai, kas ten jau yra PDF.
Duodi žmogui, jis supildo, pasiimi ir viskas. Ar ne taip kažką galvojai? :D

**Comment by vaidasvt** [comment]
Aš turiu omeny, kad jeigu duočiau kolegoms kokiam darbe pildyti, tai aš nežinau jų asmens kodų ar adresų taip paprastai. Tad jie patys supildytų ant pusgaminio, pasiimam tuos lapus ir tada vėliau nešim VMI.

**Comment by grinkus** [comment]
Iš esmės tai nėra svarbu. Mano originalus siūlymas buvo padaryt PDF'ą (ar tai html formą), kurią žmogus galėtų pats supildyti, atsispausdinti, pasirašyti ir priduoti.

**Comment by vaidasvt** [comment]
Na, gal ir nebloga mintis, bet tada klausimas ar nėra paprasčiau jam tiesiai online tą padaryti... Tas lapelis gaunasi overhead'as, nes mums reikia jį dar nunešt. Tas lapelis, matai, gaunasi toks šiek tiek prievartinis dalykas, gudravimas: duodi supildyti vietoj, kad ir šalia pastovi, pasiimi ir laisvas. Kuo mažiau žmogui darbo ir kuo greičiau :) Kitas atvejis, kai žmogus turi laiko ir gali viską pats padaryti :) Na, forma pildoma per PDF būtų visai gera opcija. Tik turėkim omeny, kad laiko jau nedaug ir liko ~2 mėn. Tad lapukai patys nesusipildys :D

**Comment by grinkus** [comment]
Pilstom iš tuščio į kiaurą. Neturiu banko, parašo, noriu duot pinigų. Nėra kaip, jei neturiu lapuko. Turiu lapuką, supildau, jaučiuosi gerai, tai dar ir į patį space'ą atnešiu. Toks approach'as niekaip netrukdo visiems kitiems -- kas kaip nori, tas taip pildo. Galų gale kuo mes daugiau galimų variantų pateiksim žmogui, kuris ieško, tuo geriau. Žmogui, kuris skuba turi būti tik link'ai į vmi ir pildymo pavyzdys. Žmogui, kuris yra space'e ir internetų privengia, turi būti lapukai. Stojam pilstyt, kiti metai irgi ateis. Nereikia galvot visada tam momentui.

**Comment by vaidasvt** [comment]
Nereikia nervintis. Jeigu yra noras padaryti tų variantų daugiau - visada tai yra gerai. Mano akimis, geriau padalinti lapukų daugiau, negu pridaryti 'n' alternatyvų juos pildyti, nes vien alternatyvos pinigų neatneš. O ar po metų dar liks tie 2 proc., aš irgi dar visiškai nebūčiau tikras.
Kitas dalykas, kartais suveikia ir taip, kad kai daug alternatyvų, tai iš to labai daug neišsirenka nei vienos...

**Comment by vaidasvt** [comment]
Ir jei atvirai, iki galo nesupratau visos diskusijos esmės šitos. PDF'us padariau, instrukcijas irgi... Kažkaip nežinau, ko dar reikia.

**Comment by grinkus** [comment]
Diskusija visiškai bereikšmė. Kaip ir sakiau -- iš tuščio į kiaurą, nes kalbam apie kelis dalykus vienu metu. Pirmas mano komentaras buvo apie tai, kaip reiktų pdf'ą prisegt prie issue. Slack'e pdf'o neradau, mačiau log'e, kad ištrintas. Papasakojau, kad TIF nelimpa. Tada pradėjom šnekėt ar kam nors būtų smagu pildyt pdf'ą.

Grįžtant prie šaknų, formuluotė site'e:
- Labas, užpildyk prašymą. Galima padaryti nuėjus į vmi deklaravimo site'ą ir užpildžius formą.
- Damn, site'as neįsileidžia, nes nesinaudoji bankais? Viskas ok! We've got you covered! Atvaryk pas mus tuo ir tuo adresu tada ir tada -- daugiau parintis nereikia, nes mes tų lapukų kalnais turim.
- Tingi atnešt? Papingink šitą mail'ą su savo adresu ir kas nors atlėks paimt (būtų amazing, bet naudoju tik kaip pavyzdį)

**Comment by vaidasvt** [comment]
Pridėjau PDF'ą, kuris supildytas slacke, bet jis toks pusiau. KOmentaras mano ten.

**Comment by dariuskt** [comment]
PDF labai prastos kokybės, pridedu [skanuotą variantą](https://cloud.githubusercontent.com/assets/3081415/13552861/04695136-e37c-11e5-8c59-a695700e322b.png)

**Comment by grinkus** [comment]
http://makerspace.lt/parama

**Comment by grinkus** [comment]
[Turėtų būt fillable PDF'as](https://github.com/makerspacelt/makerspacelt.github.io/files/174512/makerspace-parama.pdf)

**Comment by grinkus** [comment]
[Toks pat, tik ne fillable](https://github.com/makerspacelt/makerspacelt.github.io/files/174560/makerspace-parama.pdf)
